### ISSUE TITLE
A subdomain can make a domain cannot be populated

### ISSUE THREAD

**Issue by kilokang** [roobre/skydns-register#3]
With your example zone file:
```yaml
---
zone: roobre.es
records:
  '':
    type: A
    values:
      - 1.2.3.4
      - 1.2.3.5
  www:
    type: A
    values:
      - 1.2.3.4
      - 1.2.3.5
```
and with the defaults it will try to create these etcd keys:
```
/external-dns/es/roobre
/external-dns/es/roobre/www
```
`/external-dns/es/roobre` cannot be a key and a subfolder of other key.
